export const FETCH_THROTTLE = 1000

//=====================================
//  Quantities
//-------------------------------------

export const ITEMS_ON_PAGE = 8
export const REVIEWS_SLIDES_TO_SHOW = 10
export const NEWS_IN_SLIDER = 5


//=====================================
//  Fetched data types
//-------------------------------------

export const NEWS_PREVIEWS_COLLECTION = 'NEWS_PREVIEWS_COLLECTION'
export const NEWS_SLIDES_COLLECTION = 'NEWS_SLIDES_COLLECTION'
export const NEWS_ENTITY = 'NEWS_ENTITY'

export const SPECIALS_PREVIEWS_COLLECTION = 'SPECIALS_PREVIEWS_COLLECTION'
export const SPECIALS_SLIDES_COLLECTION = 'SPECIALS_SLIDES_COLLECTION'
export const SPECIALS_ENTITY = 'SPECIALS_ENTITY'

export const DENTISTS_PREVIEWS_COLLECTION = 'DENTISTS_PREVIEWS_COLLECTION'
export const DENTISTS_OPTIONS_COLLECTION = 'DENTISTS_OPTIONS_COLLECTION'
export const DENTISTS_ENTITY = 'DENTISTS_ENTITY'

export const SERVICES_CATEGORIES_COLLECTION = 'SERVICES_CATEGORIES_COLLECTION'
export const SERVICES_COLLECTION = 'SERVICES_COLLECTION'
export const SERVICES_BY_CATEGORY_COLLECTION = 'SERVICES_BY_CATEGORY_COLLECTION'
export const CATEGORY_PAGE_CONTENT = 'CATEGORY_PAGE_CONTENT'

export const REVIEWS_COLLECTION = 'REVIEWS_COLLECTION'
export const REVIEWS_SLIDES_COLLECTION = 'REVIEWS_SLIDES_COLLECTION'

export const QUESTIONS_COLLECTION = 'QUESTIONS_COLLECTION'


export const paginationDataTypes = [
  NEWS_PREVIEWS_COLLECTION,
  SPECIALS_PREVIEWS_COLLECTION,
  DENTISTS_PREVIEWS_COLLECTION,
  QUESTIONS_COLLECTION,
  REVIEWS_COLLECTION
]

export const articlePageDataTypes = [
  NEWS_ENTITY,
  SPECIALS_ENTITY,
  DENTISTS_ENTITY
]

export const dataTypes = {
  NEWS_PREVIEWS_COLLECTION,
  NEWS_SLIDES_COLLECTION,
  NEWS_ENTITY,
  SPECIALS_SLIDES_COLLECTION,
  SPECIALS_PREVIEWS_COLLECTION,
  SPECIALS_ENTITY,
  DENTISTS_PREVIEWS_COLLECTION,
  DENTISTS_OPTIONS_COLLECTION,
  DENTISTS_ENTITY,
  SERVICES_CATEGORIES_COLLECTION,
  SERVICES_COLLECTION,
  SERVICES_BY_CATEGORY_COLLECTION,
  CATEGORY_PAGE_CONTENT,
  REVIEWS_COLLECTION,
  REVIEWS_SLIDES_COLLECTION,
  QUESTIONS_COLLECTION
}
